---

- name: Install Node packages
  apt: name={{ item }} state=installed
  with_items:
    - nodejs
    - npm
    - nodejs-legacy
  tags: packages

- name: Install NPM packages
  npm: name={{ item }} global=yes
  with_items:
    - grunt-cli 
    - karma
  tags: packages

