---

- name: Install firewall packages
  apt: name={{ item }} state=installed
  with_items:
    - ufw
  tags: packages

- name: Configure firewall default policy
  ufw: state=enabled policy=deny direction=incoming
  
- name: Configure firewall
  ufw: rule=allow port={{ item }}
  with_items:
    - ssh
    - http
    - https

    #todo: 8983 for dev

