---

- name: Remove node_modules (so collectstatic doesn't fail to remove it)
  #note: would be good to avoid this for faster re-deploys when run_grunt=yes, but
  #      doing so via permissions (allowing collectstatic to delete) stops node/npm finding grunt files/modules
  file: path={{ app_path }}/static/js/node_modules state=absent
  when: run_collectstatic

- name: Run collectstatic
  django_manage:
    command: collectstatic --clear --noinput --no-default-ignore
    app_path: "{{ app_path }}/bin"
    virtualenv: "{{ app_path }}"
    settings: "{{ project_name }}.settings.{{ deploy_env }}"
  sudo: yes
  sudo_user: django
  when: run_collectstatic

- name: Install Node packages
  apt: name={{ item }} state=installed
  with_items:
    - nodejs
    - npm
    - nodejs-legacy
  tags: packages
  when: run_grunt

- name: Upgrade NPM and install NPM build packages
  npm: name={{ item }} global=yes
  with_items:
    - npm
    - grunt-cli 
    - karma
  tags: packages
  when: run_grunt
  
- name: Install NPM application packages
  npm: path={{ app_path }}/static/js name={{ item }}
  with_items:
    -
  when: run_grunt
  
- name: Grunt build
  command: chdir={{ app_path }}/static/js grunt build
  when: run_grunt
