---

- name: Install Node packages
  apt: name={{ item }} state=installed
  with_items:
    - nodejs
    - npm
    - nodejs-legacy
  tags: packages

- name: Install NPM packages
  npm: name={{ item }} global=yes
  with_items:
    - grunt-cli 
    - karma
  tags: packages

- name: Copy checkout static into site
  shell: "cp -a -R {{ checkout_path }}/{{ project_name }}/static {{ app_path }}/static creates={{ app_path }}/static"
