---

- name: Create virtualenv
  command: virtualenv {{ app_path }}
           creates="{{ app_path }}/bin/activate"

- name: Install packages required by the Django app
  pip: virtualenv={{ app_path }}
       requirements={{ requirements_file }}
       chdir="{{ checkout_path }}/{{ project_name }}"
  tags: packages

- name: Install application egg
  pip: virtualenv={{ app_path }}
       name="."
       chdir="{{ checkout_path }}/{{ project_name }}"
       extra_args="-U --no-deps"
  tags: packages
