---

- name: Install Apache
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - apache2-utils
    - libapache2-mod-wsgi
  tags: packages
  notify: Restart Apache

- name: Enable modules
  apache2_module: state=present name={{ item }}
  with_items:
    - alias
    - proxy_http
    - rewrite
    - ssl
    - status
    - wsgi
    - headers
  notify: Restart Apache

- name: Disable default site
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent
  notify: Restart Apache

- name: Disable default-ssl site
  file:
    path: "/etc/apache2/sites-enabled/000-default-ssl"
    state: absent
  notify: Restart Apache
